paths:
  /swagger:
    get:
      responses:
        200:
          description: Success
          schema:
            type: object

  /cron:
    get:
      responses:
        200:
          description: Success
          schema:
            type: object

  /mqtt:
    get:
      responses:
        200:
          description: Success
          schema:
            type: object

  /sqs:
    get:
      responses:
        200:
          description: Success
          schema:
            type: object

  /udp:
    get:
      responses:
        200:
          description: Success
          schema:
            type: object
